name: Test Upload in GDrive
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        
env:
  REPO_URL: https://github.com/manvisdr/ROOterSource2102
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config_rpi1_rooter21
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: false
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Jakarta

jobs:
   build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
      
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
            
    - name: Generate Toolchain Image
      id: generate
      run: |
          export FILE_NAME="ROOTER21.2-cache-bcm2708.tar.gz"
          mkdir ~/work/Build-Openwrt/Build-Openwrt/output
          tar -cvzf output/ROOTER21.2-cache-bcm2708.tar.gz openwrt/*
          cd output
          split -b 10M ROOTER21.2-cache-bcm2708.tar.gz "PART-ROOTER21.2-cache-bcm2708.tar.gz.part"
          rm ROOTER21.2-cache-bcm2708.tar.gz
   
      # Upload to Drive
    - name: Upload 1 to Google Drive
      uses: Jodebu/upload-to-drive@master
      with:
       target: output/*
       credentials: ${{ secrets.DRIVE_CRED }}
       folder: ${{ secrets.DRIVE_FOLDER }}
       
    
