name: Store readme in Drive
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
   build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
            
    - name: Generate Toolchain Image
      id: generate
      run: |
          export FILE_NAME="ROOTER21.2-cache-bcm2708.tar.gz"
          mkdir ~/work/Build-Openwrt/Build-Openwrt/output
          tar -cvzf output/ROOTER21.2-cache-bcm2708.tar.gz openwrt/*
          cd output
          split -b 10M ROOTER21.2-cache-bcm2708.tar.gz "PART-ROOTER21.2-cache-bcm2708.tar.gz.part"
          rm ROOTER21.2-cache-bcm2708.tar.gz
   
      # Upload to Drive
    - name: Upload README.md to Google Drive
      uses: Jodebu/upload-to-drive@master
      with:
       target: output
       credentials: secrets.DRIVE_CRED
       folder: secrets.DRIVE_FOLDER
